backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "frontendProjects"
    label: "frontendProjects"
    folder: "content/frontendProjects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "description", widget: "string" }
      - { label: "Technologies", name: "technologies", widget: "list" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Repo", name: "repo", widget: "string" }
      - { label: "Screenshots", name: "screenshots", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "backendProjects"
    label: "backendProjects"
    folder: "content/backendProjects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "description", widget: "string" }
      - { label: "Technologies", name: "technologies", widget: "list" }
      - { label: "Documentation", name: "docs", widget: "string" }
      - { label: "Repo", name: "repo", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
